### ISSUE TITLE
CPU会爆满

### ISSUE THREAD

**Issue by xiaoshuaiyu1993** [Coolll/WQLPaoMaView#2]
是用递归这种形式去实现循环动画 是没法真正意义上停止的，CPU会暴涨

**Comment by Coolll** [comment]
递归时，并没有创建新的对象呀，我这边没有看到CPU暴涨的情况，你能把你的操作详细描述一下吗？比如说是运行多久？

**Comment by Coolll** [comment]
已经解决～
